In [2]:
# %pip install pandas
import pandas as pd

In [13]:
df = pd.DataFrame({
    'col1': [1,2,3,4,5],
    'col2': [3,4,8,9,5],
    # 'col3': 'samir bhoyar data engineer'
    'col3': 'samir bhoyar is data engineer'.split()
})
df

   col1  col2      col3
0     1     3     samir
1     2     4    bhoyar
2     3     8        is
3     4     9      data
4     5     5  engineer

In [15]:
df['col4']= df['col1']**2
df

   col1  col2      col3  col4
0     1     3     samir     1
1     2     4    bhoyar     4
2     3     8        is     9
3     4     9      data    16
4     5     5  engineer    25

In [16]:
def cond(words):
    list=[]
    for word in words:
        if word[0]=='s':
           list.append('s') 
        else: 
            list.append('z')    
    return list
df['col5'] = cond(df['col3'])
df

   col1  col2      col3  col4 col5
0     1     3     samir     1    s
1     2     4    bhoyar     4    z
2     3     8        is     9    z
3     4     9      data    16    z
4     5     5  engineer    25    z

In [17]:
df['col6']= df['col1'].apply(lambda x: 'even' if  x/2==0 else 'odd' )
df

   col1  col2      col3  col4 col5 col6
0     1     3     samir     1    s  odd
1     2     4    bhoyar     4    z  odd
2     3     8        is     9    z  odd
3     4     9      data    16    z  odd
4     5     5  engineer    25    z  odd

In [20]:
df['col7'] = df['col3'].apply(len)
df

   col1  col2      col3  col4 col5 col6  col7      col8
0     1     3     samir     1    s  odd     5  1.098612
1     2     4    bhoyar     4    z  odd     6  1.386294
2     3     8        is     9    z  odd     2  2.079442
3     4     9      data    16    z  odd     4  2.197225
4     5     5  engineer    25    z  odd     8  1.609438

In [21]:
import math
df['col8'] = df['col2'].apply(math.log)
df

   col1  col2      col3  col4 col5 col6  col7      col8
0     1     3     samir     1    s  odd     5  1.098612
1     2     4    bhoyar     4    z  odd     6  1.386294
2     3     8        is     9    z  odd     2  2.079442
3     4     9      data    16    z  odd     4  2.197225
4     5     5  engineer    25    z  odd     8  1.609438